### ISSUE TITLE
Jake's face when switching deck set

### ISSUE THREAD

**Issue by TailBit** [shishkabob27/CardWarsKingdom-Issues#14]
**Describe the bug**
Jake is displayed without his mouth for a moment, when you swap deck

**To Reproduce**
1. Battle
2. Select anyone
3. Go so you see the 3d model of both fighers
4. swap between decks

**Expected behavior**
To his face to remain in place

**Screenshots**
He is scary like this
![image](https://github.com/shishkabob27/CardWarsKingdom-Issues/assets/19555561/adab28b2-03a7-4cee-8656-83baa8b4b5da)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Comment by shishkabob27** [comment]
This should be fixed in v1.18.0
