### ISSUE TITLE
Annoying Glitch to get infinite creature fragments

### ISSUE THREAD

**Issue by cSikorsky** [shishkabob27/CardWarsKingdom-Issues#16]
**Describe the bug**
I recently learned of a Glitch that apparently all CWK players are using to get infinite shards with a single card of the creature they want to awaken and increase their passive.

**To Reproduce**
I show a video below, but I write to make the Glitch 

you put a creature to defragment: 2 you will defragment it: 3 before the fragments are saved to the inventory you remove the creature card: 4 and repeat the process

**Expected behavior**
I think this Glitch works because of the visual effect that does not exist when you put the card to defragment, it appears that you can defragment but the card is invisible

**Smartphone (please complete the following information):**
 - Device: POCO F4 GT
 - OS: ANDROID 12
 - Version 1.0.17

**Additional context**
I understand that it can be difficult to obtain creatures, but this is already abusing haha.

https://github.com/shishkabob27/CardWarsKingdom-Issues/assets/157223796/29074acd-4249-42ed-b3f2-dc18d79f811a

**Comment by shishkabob27** [comment]
I think I'll leave this bug in as it was in the original CWK. Also the economy is kinda messed up as there are no microtransactions
