### ISSUE TITLE
Internet connection pop up

### ISSUE THREAD

**Issue by HazeDolores** [shishkabob27/CardWarsKingdom-Issues#21]
Can't enter the game because of this pop up
![Screenshot_20240201_131237_com 
shishkabob cwkingdom](https://github.com/shishkabob27/CardWarsKingdom-Issues/assets/158463312/f768d70e-a713-44cb-9109-965e80244369)

**Comment by AhmedMonerAhmed** [comment]
The game basically doesn't have any saving data to retrieve the account you were on at the level, and this is the worst thing in the game.

**Comment by shishkabob27** [comment]
Server is back up
