### ISSUE TITLE
Opponent's hand not decreasing as they play cards

### ISSUE THREAD

**Issue by Robberino** [shishkabob27/CardWarsKingdom-Issues#23]
**Describe the bug**
When the computer player plays their cards, the number of cards visible in their hand does not decrease.

**To Reproduce**
1. Play a game. (Choose an opponent with a single creature with a high drag attack value to see the bug on the first turn)
2. Wait for the opponent to play a card from their hand.
3. The opponent still is holding the same number of cards as before.

**Expected behavior**
The visual of the cards in their hand should accurately reflect how many cards they actually are holding and can therefore use. Interestingly, the computer can still gain cards when drag attacking, but won't lose any cards when playing them. This leads to strange situations where the number of cards in their hand seems to be overflowing past the limit of 10.

**Smartphone (please complete the following information):**
 - Device: Galaxy S22
 - OS: Android 14
 - Version 1.0.17

**Additional context**
Seeing the number of cards the opponent is holding is a huge part of strategizing and deciding what you should do next. Not knowing this information means certain decks/cards have an advantage.

P.S. It also seems that this behavior is mirrored in the fact that whenever the computer plays a new creature, that creature's indicator card on the left of the opponent's face doesn't disappear either. This makes it so you can't tell how many creatures the opponent has left unless you've been keeping track yourself.

**Comment by shishkabob27** [comment]
This has been fixed in v1.18.0
