### ISSUE TITLE
"A crash has occurred in PvP, returning to town" error keeps occurring

### ISSUE THREAD

**Issue by cSikorsky** [shishkabob27/CardWarsKingdom-Issues#26]
**Describe the bug**
This error has been occurring since 1.18.0 and 1.18.1, there is nothing more to say, When you return to the city the game freezes completely, only the gyroscope works, but it doesn't let you interact with anything

**Expected behavior**
Approximately 30 seconds into playing a PvP, you get the message that an error has occurred

**Smartphone (please complete the following information):*

 - Device: POCO F4 GT
 - OS: ANDROID 12
 - Version 1.18.1

https://github.com/shishkabob27/CardWarsKingdom-Issues/assets/157223796/a8f71905-322a-44ba-abd7-ea5f35b28b24

**Comment by shishkabob27** [comment]
Fixed in 1.18.2
